// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-EE4vBqMgUV-PbevViGN1gsOXPR6rc4',
    appId: '1:168725709522:web:3e7a6d44a403c48804a30b',
    messagingSenderId: '168725709522',
    projectId: 'coastalheaven-97690',
    authDomain: 'coastalheaven-97690.firebaseapp.com',
    storageBucket: 'coastalheaven-97690.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWETy1wQxyzqcRJVF7G__zdX2j1sk1yTY',
    appId: '1:168725709522:android:bac9d350b7ad0c5604a30b',
    messagingSenderId: '168725709522',
    projectId: 'coastalheaven-97690',
    storageBucket: 'coastalheaven-97690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTSHSlR0RNTdxJp3s4qEc7RsxEtZwM4-A',
    appId: '1:168725709522:ios:d153fad1b83eada504a30b',
    messagingSenderId: '168725709522',
    projectId: 'coastalheaven-97690',
    storageBucket: 'coastalheaven-97690.appspot.com',
    iosBundleId: 'com.example.coastalHeaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTSHSlR0RNTdxJp3s4qEc7RsxEtZwM4-A',
    appId: '1:168725709522:ios:bcc36cdbc9c1613b04a30b',
    messagingSenderId: '168725709522',
    projectId: 'coastalheaven-97690',
    storageBucket: 'coastalheaven-97690.appspot.com',
    iosBundleId: 'com.example.coastalHeaven.RunnerTests',
  );
}
